### 0. Miscellaneous

In [34]:
import math
import numpy as np
import random
import datetime
import os
import json

In [35]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fma', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [36]:
"{:.4f}".format(math.pi)

'3.1416'

In [37]:
math.log(32,2)

5.0

In [38]:
import math as mt #alias 

In [39]:
mt.pi

3.141592653589793

In [40]:
from math import *
from numpy import *
print(pi, log(32,2))
"""
These kinds of "star imports" can occasionally lead to weird, 
difficult-to-debug situations.

The problem in this case is that the math and numpy modules 
both have functions called log, but they have different semantics. 
Because we import from numpy second, its log overwrites (or "shadows") 
the log variable we imported from math
"""

TypeError: return arrays must be of ArrayType

In [41]:
[3,2,5] + 10

TypeError: can only concatenate list (not "int") to list

In [42]:
array([5,3,6,7]) + 10

array([15, 13, 16, 17])

In [43]:
alist = [[1,2,3],[5,6,7]]
arr = numpy.asarray(alist)
print("{}\n{}".format(alist,arr))

[[1, 2, 3], [5, 6, 7]]
[[1 2 3]
 [5 6 7]]


In [44]:
arr[1,-1] # arr[row, position]

np.int64(7)

### 1. Builtin modules

In [45]:
#Math module
print(math.sqrt(144))
print(math.pi)
print(math.log(32,2))
print(math.ceil(4.4))
print(math.floor(4.9))

12.0
3.141592653589793
5.0
5
4


In [46]:
#random 
random.seed(42)
print(random.random())
print(random.randint(1,100))
random.seed(42)
print(random.random())

data = [1,2,3,4,5,6,7,8,9,0]
random.shuffle(data)
print(data)
sample = random.sample(data,3)
print(sample)


0.3745401188473625
93
0.3745401188473625
[4, 0, 1, 9, 6, 3, 2, 7, 5, 8]


TypeError: random_sample() takes at most 1 positional argument (2 given)

In [47]:
#datetime
now = datetime.datetime.now()
print(now.strftime("%y-%m-%d %H:%M"))
today = datetime.datetime.today()
print(today)

26-04-22 16:20
2026-04-22 16:20:46.477009


In [48]:
#Operating system
print(os.getcwd())
print(os.listdir("."))
os.makedirs("Miscellaneous",exist_ok=True)

C:\Users\chira\OneDrive\Desktop\AI_DATA_Py\AI_ML_Prep\Daily_Practice
['.ipynb_checkpoints', 'config.json', 'day_1.ipynb', 'Day_2.ipynb', 'Day_3.ipynb', 'Day_4.ipynb', 'Day_5.ipynb', 'Miscellaneous', 'run_py.txt', 'scores.txt', 'stats_utils.py', 'students.csv', 'text.txt', 'text_2.txt', 'text_copy.txt', 'watch.png', 'watch_copy.png', '__pycache__']


In [49]:
#JSON

config = {"model":"RandomForest", "n_estimators":100, "max_depth" : 5}
with open("config.json","w") as f:
    json.dump(config, f, indent=2)

with open("config.json","r") as f:
    loaded = json.load(f)

print(loaded['model'])

RandomForest


In [50]:
# Creating arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a.shape)      # (5,)
print(a.dtype)      # int64
print(a.ndim)       # 1


(5,)
int64
1


In [51]:
# NumPy vs Python list — key difference
python_list = [1, 2, 3, 4, 5]
print(python_list * 2)  # [1,2,3,4,5,1,2,3,4,5]  — repeats list
print(a * 2)            # [ 2  4  6  8 10]         — element-wise!

# Vectorised operations — no loops needed
print(a + b)            # [11 22 33 44 55]
print(a * b)            # [ 10  40  90 160 250]
print(a ** 2)           # [ 1  4  9 16 25]
print(np.sqrt(b))       # [ 3.16  4.47  5.47  6.32  7.07]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [52]:
# Creating arrays quickly
zeros    = np.zeros(5)
ones     = np.ones(5)
rng      = np.arange(0, 10, 2)       # [0 2 4 6 8]
linspace = np.linspace(0, 1, 5)      # [0. 0.25 0.5 0.75 1.]
rand_arr = np.random.rand(5)         # 5 random floats
print(zeros, ones, rng, linspace)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


In [53]:
# 2D arrays — matrices (used constantly in ML)
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.shape)     # (3, 3)
print(matrix[0])        # first row  → [1 2 3]
print(matrix[:, 1])     # second col → [2 5 8]
print(matrix[1, 2])     # row 1, col 2 → 6

(3, 3)
[1 2 3]
[2 5 8]
6


In [54]:
# Stats functions
scores = np.array([85, 92, 67, 78, 55, 91, 88, 73])
print(f"Mean   : {np.mean(scores):.2f}")
print(f"Median : {np.median(scores):.2f}")
print(f"Std    : {np.std(scores):.2f}")
print(f"Min/Max: {np.min(scores)} / {np.max(scores)}")

Mean   : 78.62
Median : 81.50
Std    : 12.18
Min/Max: 55 / 92


In [55]:
# Boolean masking — VERY important, used constantly in DS
mask = scores > 80
print(mask)                  # [True True False True ...]
print(scores[mask])          # only scores above 80
print(scores[scores > 80])   # same thing, shorthand

[ True  True False False False  True  True False]
[85 92 91 88]
[85 92 91 88]


In [58]:
!python stats_utils.py 

In [60]:
import stats_utils as su #our own library file

data = [85, 92, 67, 78, 55]
print(su.mean(data))
print(su.std_dev(data))
print(su.normalize(data))

75.4
13.124023773218335
[0.8108108108108109, 1.0, 0.32432432432432434, 0.6216216216216216, 0.0]
