In [18]:
import math
import numpy

In [2]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [10]:
"{:.4f}".format(math.pi)

'3.1416'

In [11]:
math.log(32,2)

5.0

In [12]:
import math as mt #alias 

In [13]:
mt.pi

3.141592653589793

In [15]:
from math import *
from numpy import *
print(pi, log(32,2))
"""
These kinds of "star imports" can occasionally lead to weird, 
difficult-to-debug situations.

The problem in this case is that the math and numpy modules 
both have functions called log, but they have different semantics. 
Because we import from numpy second, its log overwrites (or "shadows") 
the log variable we imported from math
"""

TypeError: return arrays must be of ArrayType

In [16]:
[3,2,5] + 10

TypeError: can only concatenate list (not "int") to list

In [17]:
array([5,3,6,7]) + 10

array([15, 13, 16, 17])

In [19]:
alist = [[1,2,3],[5,6,7]]
arr = numpy.asarray(alist)
print("{}\n{}".format(alist,arr))

[[1, 2, 3], [5, 6, 7]]
[[1 2 3]
 [5 6 7]]


In [20]:
arr[1,-1] # arr[row, position]

7

In [23]:
import tensorflow as tf


[TensorFlow DLL Diagnostic] Analyzing: C:\Users\chira\anaconda3\Lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd
[Error] Failed to load _pywrap_tensorflow_common.dll: INITIALIZATION FAILED (0x45A) - The DLL's DllMain returned false.
    Hint: This often happens if your CPU lacks required instructions (like AVX/AVX2)
    or if the Microsoft Visual C++ Redistributable is outdated/missing.


ImportError: Traceback (most recent call last):
  File "C:\Users\chira\anaconda3\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.